kind: ModulePlugin
metadata:
  annotations:
    cpaas.io/built-in-plugin: "false" # 标识是否产品集成的插件
    cpaas.io/display-name: '{"en": "English Plugin Name", "zh": "插件中文名称"}' # 显示名称
    cpaas.io/module-name: demo-plugin # 插件名称
  labels:
    cpaas.io/module-catalog: devops # 可选，插件分类
    cpaas.io/module-name: demo-plugin # 插件名称
    cpaas.io/module-type: plugin # 固定字段
    cpaas.io/product: devops # 所属产品
  name: demo-plugin # 插件名称
spec:
  # 可选， 插件的部署限制, 仅当有限制时填写
  affinity:
    pluginAntiAffinity:
    - demo-plugin
  appReleases:
  - chartVersions:
    - name: demo/chart-sample
      releaseName: chart-sample
      version: v1.0.0
    name: demo-plugin
  deleteRiskDescription: 中文 # 可选，删除插件风险提示中文文案
  deleteRiskDescriptionEn: English # 可选，删除插件风险提示英文文案
  deleteable: true # 插件是否可以删除
  description:
    en: English # 插件功能描述，英文
    zh: 中文 # 插件功能描述，中文
  labelCluster: "true"
  logo: data:image/svg+xml;base64,xxx # logo 为 base64 后的 svg 数据，在线压缩svg工具: https://vecta.io/nano
  mainChart: demo/demo-plugin # 主 chart, 存放有插件配置项 scripts/plugin-config.yaml
  name: demo-plugin
  upgradeRiskDescription: 中文 # 可选，插件升级风险提示中文文案
  upgradeRiskDescriptionEn: English # 可选，插件升级风险提示英文文案
  upgradeRiskLevel: low # 可选，插件升级风险等级，可取值：low, middle, high
  resourcesBlockRemove: # 可选，可阻止删除插件的资源。即只有这些资源被删除后才可以删除插件
  - apiVersion: test.alauda.io/v1beta1
    kind: BlockService